### ISSUE TITLE
Plugin does not jump between files

### ISSUE THREAD

**Issue by wibotwi** [kvichans/cuda_caret_history#5]
To reproduce:
* open second file
* jump back
* expected: go to previous file
* actual: nothing happens

**Comment by kvichans** [comment]
Plugin does not help to jump between files
See readme.txt:
> Plugin tracks changes of caret position, and when caret jumps long (more than 10 lines, option), it adds history point. So plugin keeps history of long caret jumps. It gives 2 commands: move backward, move forward, they change caret using this history. Short caret movements don't add to history (but they correct current history item). History length is 5 items by default (option).

> The following scenario is working: you open file, jump to the end of file, history point is added, then "move backward" moves to begin of file. Then short editings don't change history, and "move forward" jumps to file end. Then short editings don't change history, and "move backward" jumps to file begin.*

**Comment by wibotwi** [comment]
> Plugin does not help to jump between files

Yes. that is why I opened issue. 
In other popular editors jump happens across all files.

**Comment by kvichans** [comment]
I have no plans to do it.
Try yourself - it's fun.

**Comment by wibotwi** [comment]
You sound hostile, why?
I just opened a ticket. It's a free github. Everyone has right to open a ticket. Somebody will see this ticket and will suggest a patch. This is how github works.
If you don't like this process -> you can make your code private or remove completely from github.

**Comment by kvichans** [comment]
Sorry my poor english. I want to say  you "can suggest a patch".

**Comment by wibotwi** [comment]
Is there any docs of how to write plugins?

Few questions so far:
1. all comments are in Russian, is that mandatory? Less people can make patches because of that :(
2. Several lines are "pass; # LOG".  Python would ignore this. Does CudaText run some pre-processor before calling Python?
3. File is not reformatted according to pep8. Should some other formatter be used? Or I can just go and reformat all file to pep8?

**Comment by kvichans** [comment]
> docs of how..?

It's question to @Alexey-T. I write plugins almost "always" so dont know.

---
> russian comments

Sorry. It is my mistake. I'm ready to translate all them.

---
> `# LOG` 

It's my logger (in turning off mode) to debug.

---
> pep8 

`pep8` is only recommendation to code style, but not a requirement.
Yes you are free to reformat the source.

**Comment by wibotwi** [comment]
Not only logging
some code is uncommented and also has this "pass;" style
`pass;                           from cudax_lib import log`

I'll remove it then in my PR

// Sorry. It is my mistake. I'm ready to translate all them.
I'll translate in my PR, thank you for agreeing to that
